stages:
  - mavenbuild
  - maventest
  
maven-build:            
  stage: mavenbuild
  tags:
    - springboot_tag      # <-- change to your runner's tag
  script:
    - cd Backend        # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn package
  only:
    refs:
      - Jayden_CICD
    changes:
      - Backend/**/*


maven-test:             
  stage: maventest
  tags:
    - springboot_tag     # <-- change to your runner's tag
  script:
    - cd Backend       # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn test
  only:
    refs:
      - Jayden_CICD
    changes:
      - Backend/**/*
stages:
  - mavenbuild
  - maventest
  
maven-build:            
  stage: mavenbuild
  tags:
    - springboot_tag      # <-- change to your runner's tag
  script:
    - cd Backend        # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn package
  only:
    refs:
      - YOURNAME_CICD
    changes:
      - Backend/**/*


maven-test:             
  stage: maventest
  tags:
    - yourname_tag     # <-- change to your runner's tag
  script:
    - cd Backend       # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn test
  only:
    refs:
      - YOURNAME_CICD
    changes:
      - Backend/**/*

  - mavenbuild
  - maventest
  
maven-build:            
  stage: mavenbuild
  tags:
    - Jayden
    - springboot_tag      # <-- change to your runner's tag
  script:
    - cd springboot_example        # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn package
  only:
    refs:
      - Jayden_CICD
    changes:
      - Backend/**/*


maven-test:             
  stage: maventest
  tags:
    - Jayden
    - springboot_tag     # <-- change to your runner's tag
  script:
    - cd springboot_example       # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn test
  only:
    refs:
      - Jayden_CICD
    changes:
      - Backend/**/*
