stages:
  - mavenbuild
  - maventest
  
maven-build:            
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd "Backend/Backend app/tutorials-springboot_unit2_1_onetoone/springboot_example"
    - mvn package
  only:
    refs:
      - Jayden_CICD
    changes:
      - Backend/**/*


maven-test:             
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd "Backend/Backend app/tutorials-springboot_unit2_1_onetoone/springboot_example"
    - mvn test
  only:
    refs:
      - Jayden_CICD
    changes:
      - Backend/**/*
